# Generated by Django 4.0.5 on 2022-06-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(help_text='Resumen de la película', max_length=240),
        ),
    ]
